#@ load("@ytt:template", "template")

#@ load("ruby.star", "truffleruby_versions")
#@ all_truffleruby_versions = []
#@ all_truffleruby_versions.extend(truffleruby_versions["beta"])
#! 2021-03-10 omit stable until the changes related to nokogiri are shipping in v22
#! #@ all_truffleruby_versions.extend(truffleruby_versions["supported"])

#@ compile_flag_combos = ["--disable-system-libraries --disable-static",
#@                        "--disable-system-libraries --enable-static",
#@                        "--enable-system-libraries",
#@                       ]

---
#@ def registry_image(image_repo, image_tag):
platform: linux
image_resource:
  type: registry-image
  source:
    repository: #@ image_repo
    tag: #@ image_tag
#@ end

---
resource_types:
  - name: pull-request
    type: registry-image
    source:
      repository: teliaoss/github-pr-resource


resources:
  - name: ci
    type: git
    icon: cog
    source:
      uri: https://github.com/sparklemotion/nokogiri/
      branch: main
      disable_ci_skip: true #! always get the latest pipeline configuration
  - name: nokogiri
    type: git
    icon: "github"
    check_every: 5m
    webhook_token: ((nokogiri-main-webhook-token))
    source:
      uri: https://github.com/sparklemotion/nokogiri/
      branch: main
      ignore_paths:
        - "*.md"
        - "concourse/**"
        - "suppressions/**"
        - ".github/**"
        - "Vagrantfile"
  - name: nokogiri-pr
    type: pull-request
    icon: github
    check_every: 15m
    webhook_token: ((nokogiri-pr-webhook-token))
    source:
      repository: sparklemotion/nokogiri
      access_token: ((github-repo-status-access-token))
      ignore_drafts: true
      ignore_paths:
        - "*.md"
        - "concourse/"
        - "suppressions/"
        - ".github/"
        - "Vagrantfile"

jobs:
#@ previous_job_name = None
#@ for ruby_version in all_truffleruby_versions:
#@ job_name = "truffle-{}".format(ruby_version)
  - name: #@ job_name
    public: true
    plan:
      - get: ci
      - get: nokogiri
        trigger: true
        #@ if/end previous_job_name:
        passed: #@ [previous_job_name]
      #@ for compile_flags in compile_flag_combos:
      - task: rake-test
        config:
          "_": #@ template.replace(registry_image("flavorjones/nokogiri-test", "truffle-{}".format(ruby_version)))
          inputs: [{name: ci}, {name: nokogiri}]
          params:
            COMPILE_FLAGS: #@ compile_flags
          run: { path: ci/concourse/tasks/rake-test/run.sh }
      #@ end
#@ previous_job_name = job_name
#@ end

#@ previous_job_name = None
#@ for ruby_version in all_truffleruby_versions:
#@ job_name = "truffle-pr-{}".format(ruby_version)
  - name: #@ job_name
    public: true
    plan:
      - get: ci
      - get: nokogiri-pr
        trigger: true
        version: every
        #@ if/end previous_job_name:
        passed: #@ [previous_job_name]
      #@ for compile_flags in compile_flag_combos:
      - task: rake-test
        config:
          "_": #@ template.replace(registry_image("flavorjones/nokogiri-test", "truffle-{}".format(ruby_version)))
          inputs: [{name: ci}, {name: nokogiri-pr, path: nokogiri}]
          params:
            COMPILE_FLAGS: #@ compile_flags
          run: { path: ci/concourse/tasks/rake-test/run.sh }
      #@ end
#@ previous_job_name = job_name
#@ end
