language: ruby
# Start OSX builds before Linux, because they take longer.
os:
  - osx
  - linux
rvm: # http://rubies.travis-ci.org/
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4.0 # https://github.com/travis-ci/travis-ci/issues/7848
matrix:
  exclude:
    - os: osx
      rvm: 1.9
    - os: osx
      rvm: 2.0
    - os: osx
      env: WITH_LIBXML=false V=1
env:
  - WITH_LIBXML=true V=1
  - WITH_LIBXML=false V=1
before_script: |
  if [ "$WITH_LIBXML" == "false" ]; then
    sudo apt-get remove libxml2-dev
  fi
sudo: required
cache: bundler
